### ISSUE TITLE
no dc:format for annotatable version

### ISSUE THREAD

**Issue by chrmor** [DM2E/dm2e-mappings#54] opened 2014-03-03 21:44 UTC
http://data.dm2e.eu/data/rdf/resourcemap/ub-ffm/sammlungen/320380742_phys5001862/20140301004538912

**Comment by knepper** [comment] 2014-03-04 08:23
My data are looking like this

``` xml

   <edm:WebResource rdf:about="http://sammlungen.ub.uni-frankfurt.de/msma/download/webcache/1000/5001862">
      <dc:format>image/jpeg</dc:format>
   </edm:WebResource>
```

How can I check this in pubby?

**Comment by knepper** [comment] 2014-03-04 08:31
see #52

**Comment by kba** [comment] 2014-03-04 09:29
Caused by #51

**Comment by kba** [comment] 2014-03-04 10:09
Fixed by #51.

**Closed as completed by kba** 2014-03-04 10:09 UTC
Labels: sammlungen, pundit-showblocker, pubby
